name: AT2-EXPERIMENTAL

on:
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_review:
    types: 
      - submitted
    branches:
    - master
    - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gcc10-openmpi416-EXPERIMENTAL:
    runs-on: [self-hosted, gcc-10.3.0_openmpi-4.1.6]
    if: ${{ github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.review.state == 'APPROVED' }}
    steps:
      - name: env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
      - name: module list
        shell: bash
        run: |
          bash -l -c "module list"
          printenv PATH
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ github.token }}
      - name: make dirs
        working-directory: /
        run: |
          mkdir -p /home/Trilinos/src/Trilinos
          mkdir -p /home/Trilinos/build
      - name: Clone trilinos
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - name: Repo status
        run: |
          git fetch --all
          pwd
          ls -lhat
          git status
          git branch -vv
          git branch -a
      - name: get dependencies
        working-directory: ./packages/framework
        run: |
          bash -l -c "./get_dependencies.sh --container"
      - name: PullRequestLinuxDriverTest.py
        shell: bash -l {0}
        working-directory: /home/Trilinos/build
        run: |
          export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/packages/framework/GenConfig
          export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/packages/framework/pr_tools

          sed -i "/\[rhel8\]/a `cat /etc/hostname`" /home/runner/_work/Trilinos/Trilinos/packages/framework/ini-files/supported-systems.ini
          printf "\n\n\n"

          echo "image: ${AT2_IMAGE:-unknown}"

          python3 ${GITHUB_WORKSPACE}/packages/framework/pr_tools/PullRequestLinuxDriverTest.py \
            --source-repo-url ${GITHUB_WORKSPACE} \
            --target-repo-url ${GITHUB_WORKSPACE} \
            --target-branch-name ${{ github.event.pull_request.base.ref }} \
            --pullrequest-build-name PR-${{ github.event.pull_request.number }} \
            --genconfig-build-name rhel8_gcc-openmpi_debug_shared_no-kokkos-arch_no-asan_complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables \
            --pullrequest-number ${{ github.event.pull_request.number }} \
            --jenkins-job-number 0 \
            --pullrequest-env-config-file ${GITHUB_WORKSPACE}/packages/framework/pr_tools/trilinos_pr.ini \
            --pullrequest-gen-config-file ${GITHUB_WORKSPACE}/packages/framework/GenConfig/src/gen-config.ini \
            --workspace-dir /home/runner/_work/Trilinos \
            --source-dir ${GITHUB_WORKSPACE} \
            --build-dir /home/Trilinos/build \
            --dashboard-build-name `cat /etc/hostname` \
            --ctest-driver /home/runner/_work/Trilinos/Trilinos/cmake/SimpleTesting/cmake/ctest-driver.cmake \
            --ctest-drop-site sems-cdash-son.sandia.gov/cdash \
            --filename-subprojects ./package_subproject_list.cmake \
            --filename-packageenables ./packageEnables.cmake

  gcc830-serial-EXPERIMENTAL:
    runs-on: [self-hosted, gcc-8.3.0_serial]
    if: ${{ github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.review.state == 'APPROVED' }}
    steps:
      - name: env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
      - name: module list
        shell: bash
        run: |
          bash -l -c "module list"
          printenv PATH
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ github.token }}
      - name: make dirs
        working-directory: /
        run: |
          mkdir -p /home/Trilinos/src/Trilinos
          mkdir -p /home/Trilinos/build
      - name: Clone trilinos
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - name: Repo status
        run: |
          git fetch --all
          pwd
          ls -lhat
          git status
          git branch -vv
          git branch -a
      - name: get dependencies
        working-directory: ./packages/framework
        run: |
          bash -l -c "./get_dependencies.sh --container"
      - name: PullRequestLinuxDriverTest.py
        shell: bash -l {0}
        working-directory: /home/Trilinos/build
        run: |
          export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/packages/framework/GenConfig
          export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/packages/framework/pr_tools

          sed -i "/\[rhel8\]/a `cat /etc/hostname`" /home/runner/_work/Trilinos/Trilinos/packages/framework/ini-files/supported-systems.ini
          printf "\n\n\n"

          echo "image: ${AT2_IMAGE:-unknown}"

          python3 ${GITHUB_WORKSPACE}/packages/framework/pr_tools/PullRequestLinuxDriverTest.py \
            --source-repo-url ${GITHUB_WORKSPACE} \
            --target-repo-url ${GITHUB_WORKSPACE} \
            --target-branch-name ${{ github.event.pull_request.base.ref }} \
            --pullrequest-build-name PR-${{ github.event.pull_request.number }} \
            --genconfig-build-name rhel8_gcc-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables \
            --pullrequest-number ${{ github.event.pull_request.number }} \
            --jenkins-job-number 0 \
            --pullrequest-env-config-file ${GITHUB_WORKSPACE}/packages/framework/pr_tools/trilinos_pr.ini \
            --pullrequest-gen-config-file ${GITHUB_WORKSPACE}/packages/framework/GenConfig/src/gen-config.ini \
            --workspace-dir /home/runner/_work/Trilinos \
            --source-dir ${GITHUB_WORKSPACE} \
            --build-dir /home/Trilinos/build \
            --dashboard-build-name `cat /etc/hostname` \
            --ctest-driver /home/runner/_work/Trilinos/Trilinos/cmake/SimpleTesting/cmake/ctest-driver.cmake \
            --ctest-drop-site sems-cdash-son.sandia.gov/cdash \
            --filename-subprojects ./package_subproject_list.cmake \
            --filename-packageenables ./packageEnables.cmake
